import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { Container, CssBaseline, ThemeProvider } from "@mui/material"
import theme from "@/theme"
import AppBarWithMenu from "@/components/AppBarWithMenu"

const inter = Inter({
  weight: ['400', '500', '600', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: "Heidenheim PWA",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="de">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Container maxWidth="sm" sx={{ height: "calc(100dvh - 64px)" }}>
              <AppBarWithMenu />
              {children}
            </Container>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
